"""empty message

Revision ID: c5d2f1912276
Revises: c17d4ce28abc
Create Date: 2020-11-07 17:05:04.644474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d2f1912276'
down_revision = 'c17d4ce28abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.String(), nullable=True))
    op.drop_constraint('questions_category_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('questions_category_id_fkey', 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
